# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5.xci
# IP: The module: 'trackforce_block_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5.xci
# IP: The module: 'trackforce_block_axi_gpio_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_gpio_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
