# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0.xci
# IP: The module: 'trackforce_block_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0.xci
# IP: The module: 'trackforce_block_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_block_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
