# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/trackforce_block/trackforce_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block || ORIG_REF_NAME==trackforce_block} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_processing_system7_0_0/trackforce_block_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_processing_system7_0_0 || ORIG_REF_NAME==trackforce_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_top_0_0/trackforce_block_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_top_0_0 || ORIG_REF_NAME==trackforce_block_top_0_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_0/trackforce_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_0 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_1/trackforce_block_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_1 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_1} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_2/trackforce_block_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_2 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_2} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_xbar_0/trackforce_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_xbar_0 || ORIG_REF_NAME==trackforce_block_xbar_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_auto_pc_0/trackforce_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_auto_pc_0 || ORIG_REF_NAME==trackforce_block_auto_pc_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_ps7_0_axi_periph_0/trackforce_block_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==trackforce_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_rst_ps7_0_50M_0/trackforce_block_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_rst_ps7_0_50M_0 || ORIG_REF_NAME==trackforce_block_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_0/trackforce_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_uartlite_0_0 || ORIG_REF_NAME==trackforce_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_uartlite_0_1/trackforce_block_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_uartlite_0_1 || ORIG_REF_NAME==trackforce_block_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_4/trackforce_block_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_4 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_4} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_5/trackforce_block_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_5 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_5} -quiet] -quiet

# IP: bd/trackforce_block/ip/trackforce_block_axi_gpio_0_6/trackforce_block_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==trackforce_block_axi_gpio_0_6 || ORIG_REF_NAME==trackforce_block_axi_gpio_0_6} -quiet] -quiet

# XDC: d:/GitHub/trackforceVerilog/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce_block/trackforce_block_ooc.xdc
