# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub/trackforce/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3.xci
# IP: The module: 'trackforce_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GitHub/trackforce/trackforce.vivado/trackforce.srcs/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3.xci
# IP: The module: 'trackforce_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub/trackforce/trackforce.vivado/trackforce.gen/sources_1/bd/trackforce/ip/trackforce_axi_gpio_0_3/trackforce_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'trackforce_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
