domain_path: D:\GitHub\trackforce\trackforce.vitis\trackforce_plat\export\trackforce_plat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
